//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace FOD
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FodEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FodEntities object using the connection string found in the 'FodEntities' section of the application configuration file.
        /// </summary>
        public FodEntities() : base("name=FodEntities", "FodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FodEntities object.
        /// </summary>
        public FodEntities(string connectionString) : base(connectionString, "FodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FodEntities object.
        /// </summary>
        public FodEntities(EntityConnection connection) : base(connection, "FodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Airports> Airports
        {
            get
            {
                if ((_Airports == null))
                {
                    _Airports = base.CreateObjectSet<Airports>("Airports");
                }
                return _Airports;
            }
        }
        private ObjectSet<Airports> _Airports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Settings> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Settings>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Settings> _Settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Voli> Voli
        {
            get
            {
                if ((_Voli == null))
                {
                    _Voli = base.CreateObjectSet<Voli>("Voli");
                }
                return _Voli;
            }
        }
        private ObjectSet<Voli> _Voli;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RicercheVoli> RicercheVolis
        {
            get
            {
                if ((_RicercheVolis == null))
                {
                    _RicercheVolis = base.CreateObjectSet<RicercheVoli>("RicercheVolis");
                }
                return _RicercheVolis;
            }
        }
        private ObjectSet<RicercheVoli> _RicercheVolis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AirportsCost> AirportsCosts
        {
            get
            {
                if ((_AirportsCosts == null))
                {
                    _AirportsCosts = base.CreateObjectSet<AirportsCost>("AirportsCosts");
                }
                return _AirportsCosts;
            }
        }
        private ObjectSet<AirportsCost> _AirportsCosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<City> Cities
        {
            get
            {
                if ((_Cities == null))
                {
                    _Cities = base.CreateObjectSet<City>("Cities");
                }
                return _Cities;
            }
        }
        private ObjectSet<City> _Cities;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Airports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAirports(Airports airports)
        {
            base.AddObject("Airports", airports);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Settings settings)
        {
            base.AddObject("Settings", settings);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Voli EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVoli(Voli voli)
        {
            base.AddObject("Voli", voli);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RicercheVolis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRicercheVolis(RicercheVoli ricercheVoli)
        {
            base.AddObject("RicercheVolis", ricercheVoli);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AirportsCosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAirportsCosts(AirportsCost airportsCost)
        {
            base.AddObject("AirportsCosts", airportsCost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCities(City city)
        {
            base.AddObject("Cities", city);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FodModel", Name="Airports")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Airports : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Airports object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Airports CreateAirports(global::System.String id)
        {
            Airports airports = new Airports();
            airports.Id = id;
            return airports;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FodModel", Name="AirportsCost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AirportsCost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AirportsCost object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        public static AirportsCost CreateAirportsCost(global::System.String code)
        {
            AirportsCost airportsCost = new AirportsCost();
            airportsCost.Code = code;
            return airportsCost;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Distance
        {
            get
            {
                return _Distance;
            }
            set
            {
                OnDistanceChanging(value);
                ReportPropertyChanging("Distance");
                _Distance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Distance");
                OnDistanceChanged();
            }
        }
        private Nullable<global::System.Double> _Distance;
        partial void OnDistanceChanging(Nullable<global::System.Double> value);
        partial void OnDistanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> AutorouteCost
        {
            get
            {
                return _AutorouteCost;
            }
            set
            {
                OnAutorouteCostChanging(value);
                ReportPropertyChanging("AutorouteCost");
                _AutorouteCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutorouteCost");
                OnAutorouteCostChanged();
            }
        }
        private Nullable<global::System.Double> _AutorouteCost;
        partial void OnAutorouteCostChanging(Nullable<global::System.Double> value);
        partial void OnAutorouteCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ParkDayCost
        {
            get
            {
                return _ParkDayCost;
            }
            set
            {
                OnParkDayCostChanging(value);
                ReportPropertyChanging("ParkDayCost");
                _ParkDayCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParkDayCost");
                OnParkDayCostChanged();
            }
        }
        private Nullable<global::System.Double> _ParkDayCost;
        partial void OnParkDayCostChanging(Nullable<global::System.Double> value);
        partial void OnParkDayCostChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FodModel", Name="City")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class City : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="idCity">Initial value of the IdCity property.</param>
        public static City CreateCity(global::System.Int32 idCity)
        {
            City city = new City();
            city.IdCity = idCity;
            return city;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCity
        {
            get
            {
                return _IdCity;
            }
            set
            {
                if (_IdCity != value)
                {
                    OnIdCityChanging(value);
                    ReportPropertyChanging("IdCity");
                    _IdCity = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCity");
                    OnIdCityChanged();
                }
            }
        }
        private global::System.Int32 _IdCity;
        partial void OnIdCityChanging(global::System.Int32 value);
        partial void OnIdCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FodModel", Name="RicercheVoli")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RicercheVoli : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RicercheVoli object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static RicercheVoli CreateRicercheVoli(global::System.Int32 id)
        {
            RicercheVoli ricercheVoli = new RicercheVoli();
            ricercheVoli.Id = id;
            return ricercheVoli;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Processato
        {
            get
            {
                return _Processato;
            }
            set
            {
                OnProcessatoChanging(value);
                ReportPropertyChanging("Processato");
                _Processato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Processato");
                OnProcessatoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Processato;
        partial void OnProcessatoChanging(Nullable<global::System.Boolean> value);
        partial void OnProcessatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataRicerca
        {
            get
            {
                return _DataRicerca;
            }
            set
            {
                OnDataRicercaChanging(value);
                ReportPropertyChanging("DataRicerca");
                _DataRicerca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataRicerca");
                OnDataRicercaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataRicerca;
        partial void OnDataRicercaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataRicercaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromCode
        {
            get
            {
                return _FromCode;
            }
            set
            {
                OnFromCodeChanging(value);
                ReportPropertyChanging("FromCode");
                _FromCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromCode");
                OnFromCodeChanged();
            }
        }
        private global::System.String _FromCode;
        partial void OnFromCodeChanging(global::System.String value);
        partial void OnFromCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vettore
        {
            get
            {
                return _Vettore;
            }
            set
            {
                OnVettoreChanging(value);
                ReportPropertyChanging("Vettore");
                _Vettore = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vettore");
                OnVettoreChanged();
            }
        }
        private global::System.String _Vettore;
        partial void OnVettoreChanging(global::System.String value);
        partial void OnVettoreChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FodModel", Name="Settings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Settings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Settings object.
        /// </summary>
        /// <param name="key">Initial value of the Key property.</param>
        public static Settings CreateSettings(global::System.String key)
        {
            Settings settings = new Settings();
            settings.Key = key;
            return settings;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                if (_Key != value)
                {
                    OnKeyChanging(value);
                    ReportPropertyChanging("Key");
                    _Key = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Key");
                    OnKeyChanged();
                }
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FodModel", Name="Voli")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Voli : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Voli object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Voli CreateVoli(global::System.Int32 id)
        {
            Voli voli = new Voli();
            voli.Id = id;
            return voli;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String From
        {
            get
            {
                return _From;
            }
            set
            {
                OnFromChanging(value);
                ReportPropertyChanging("From");
                _From = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("From");
                OnFromChanged();
            }
        }
        private global::System.String _From;
        partial void OnFromChanging(global::System.String value);
        partial void OnFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String To
        {
            get
            {
                return _To;
            }
            set
            {
                OnToChanging(value);
                ReportPropertyChanging("To");
                _To = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("To");
                OnToChanged();
            }
        }
        private global::System.String _To;
        partial void OnToChanging(global::System.String value);
        partial void OnToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Dal
        {
            get
            {
                return _Dal;
            }
            set
            {
                OnDalChanging(value);
                ReportPropertyChanging("Dal");
                _Dal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dal");
                OnDalChanged();
            }
        }
        private Nullable<global::System.DateTime> _Dal;
        partial void OnDalChanging(Nullable<global::System.DateTime> value);
        partial void OnDalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Al
        {
            get
            {
                return _Al;
            }
            set
            {
                OnAlChanging(value);
                ReportPropertyChanging("Al");
                _Al = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Al");
                OnAlChanged();
            }
        }
        private Nullable<global::System.DateTime> _Al;
        partial void OnAlChanging(Nullable<global::System.DateTime> value);
        partial void OnAlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Price;
        partial void OnPriceChanging(Nullable<global::System.Double> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OldPrice
        {
            get
            {
                return _OldPrice;
            }
            set
            {
                OnOldPriceChanging(value);
                ReportPropertyChanging("OldPrice");
                _OldPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OldPrice");
                OnOldPriceChanged();
            }
        }
        private Nullable<global::System.Double> _OldPrice;
        partial void OnOldPriceChanging(Nullable<global::System.Double> value);
        partial void OnOldPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsPriceChanged
        {
            get
            {
                return _IsPriceChanged;
            }
            set
            {
                OnIsPriceChangedChanging(value);
                ReportPropertyChanging("IsPriceChanged");
                _IsPriceChanged = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPriceChanged");
                OnIsPriceChangedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsPriceChanged;
        partial void OnIsPriceChangedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsPriceChangedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsBestLocalOffer
        {
            get
            {
                return _IsBestLocalOffer;
            }
            set
            {
                OnIsBestLocalOfferChanging(value);
                ReportPropertyChanging("IsBestLocalOffer");
                _IsBestLocalOffer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBestLocalOffer");
                OnIsBestLocalOfferChanged();
            }
        }
        private Nullable<global::System.Int32> _IsBestLocalOffer;
        partial void OnIsBestLocalOfferChanging(Nullable<global::System.Int32> value);
        partial void OnIsBestLocalOfferChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsBestGlobalOffer
        {
            get
            {
                return _IsBestGlobalOffer;
            }
            set
            {
                OnIsBestGlobalOfferChanging(value);
                ReportPropertyChanging("IsBestGlobalOffer");
                _IsBestGlobalOffer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBestGlobalOffer");
                OnIsBestGlobalOfferChanged();
            }
        }
        private Nullable<global::System.Int32> _IsBestGlobalOffer;
        partial void OnIsBestGlobalOfferChanging(Nullable<global::System.Int32> value);
        partial void OnIsBestGlobalOfferChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataRicerca
        {
            get
            {
                return _DataRicerca;
            }
            set
            {
                OnDataRicercaChanging(value);
                ReportPropertyChanging("DataRicerca");
                _DataRicerca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataRicerca");
                OnDataRicercaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataRicerca;
        partial void OnDataRicercaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataRicercaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromCode
        {
            get
            {
                return _FromCode;
            }
            set
            {
                OnFromCodeChanging(value);
                ReportPropertyChanging("FromCode");
                _FromCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromCode");
                OnFromCodeChanged();
            }
        }
        private global::System.String _FromCode;
        partial void OnFromCodeChanging(global::System.String value);
        partial void OnFromCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Weekend
        {
            get
            {
                return _Weekend;
            }
            set
            {
                OnWeekendChanging(value);
                ReportPropertyChanging("Weekend");
                _Weekend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weekend");
                OnWeekendChanged();
            }
        }
        private Nullable<global::System.Boolean> _Weekend;
        partial void OnWeekendChanging(Nullable<global::System.Boolean> value);
        partial void OnWeekendChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Days
        {
            get
            {
                return _Days;
            }
            set
            {
                OnDaysChanging(value);
                ReportPropertyChanging("Days");
                _Days = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Days");
                OnDaysChanged();
            }
        }
        private Nullable<global::System.Decimal> _Days;
        partial void OnDaysChanging(Nullable<global::System.Decimal> value);
        partial void OnDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vettore
        {
            get
            {
                return _Vettore;
            }
            set
            {
                OnVettoreChanging(value);
                ReportPropertyChanging("Vettore");
                _Vettore = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vettore");
                OnVettoreChanged();
            }
        }
        private global::System.String _Vettore;
        partial void OnVettoreChanging(global::System.String value);
        partial void OnVettoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Star
        {
            get
            {
                return _Star;
            }
            set
            {
                OnStarChanging(value);
                ReportPropertyChanging("Star");
                _Star = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Star");
                OnStarChanged();
            }
        }
        private Nullable<global::System.Boolean> _Star;
        partial void OnStarChanging(Nullable<global::System.Boolean> value);
        partial void OnStarChanged();

        #endregion

    
    }

    #endregion

    
}
